/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weizhong_su_YWSPU */


#ifndef _Included_com_longshao_aiquyouxi_AiQuYouXi
#define _Included_com_longshao_aiquyouxi_AiQuYouXi



#ifdef __cplusplus //cplusplus即C++
extern "C" {
#endif




JNIEXPORT jint JNICALL Java_com_longshao_aiquyouxi_AiQuYouXi_AiQuYouXiui
  (JNIEnv *, jclass);

//有引擎，但是引擎失效情况下的额外调用
JNIEXPORT void JNICALL Java_com_longshao_aiquyouxi_AiQuYouXi_AiQuYouXiAddTime
  (JNIEnv *, jclass);

JNIEXPORT void JNICALL Java_com_longshao_aiquyouxi_AiQuYouXi_AiQuYouXis
  (JNIEnv *, jclass, jfloat);


#ifdef __cplusplus
}
#endif



#endif
